### ISSUE TITLE
Crypt::Rijndael::PP depends on Crypt::Rijndael

### ISSUE THREAD

**Issue by Leont** [drzigman/crypt-rijndael-pp#1]
Crypt::Rijndael::PP test-requires Crypt::Rijndael, which kind of defeats the purpose of it.

**Comment by drzigman** [comment]
I agree.  I'll be either removing the dependencies in the tests or moving any tests that I feel should still have the dependency into an xt directory as soon as I get the chance (likely within the next week).

Thanks!
