### ISSUE TITLE
Unnecessary dependency on 5.10

### ISSUE THREAD

**Issue by Leont** [drzigman/crypt-rijndael-pp#4]
This dist depends on 5.10, only because of a single use of the `//` operator, this may be a bit suboptimal.

**Comment by drzigman** [comment]
It's an easy enough change to support older versions of Perl, I agree the change should be made.  I should be able to get to this (and the #1 changes) shortly.

Thanks for pointing this out!  I was not previously aware that // was introduced as late as 5.10.
